# Generated by Django 2.1a1 on 2019-04-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0002_auto_20190325_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
