# Generated by Django 2.1a1 on 2019-04-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0003_disease_treatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='Doctor',
            new_name='doctors',
        ),
    ]
