# Generated by Django 2.1a1 on 2019-04-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0004_auto_20190406_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='Test', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='Test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='doctors',
            field=models.ManyToManyField(blank=True, default='Test', to='finddoctor.Doctor'),
        ),
    ]
