# Generated by Django 2.1 on 2019-04-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0005_auto_20190413_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='Test', max_length=50, null=True),
        ),
    ]
