# Generated by Django 2.1a1 on 2019-04-27 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0007_auto_20190413_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apponiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='Test', max_length=50)),
                ('doctor', models.ForeignKey(default='Test', on_delete=django.db.models.deletion.CASCADE, to='finddoctor.Doctor')),
            ],
        ),
    ]
