# Generated by Django 2.1a1 on 2019-04-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0008_apponiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test', max_length=50)),
                ('phn', models.CharField(blank=True, default='Test', max_length=50, null=True)),
                ('time', models.CharField(default='Test', max_length=50)),
                ('doctor', models.ForeignKey(default='Test', on_delete=django.db.models.deletion.CASCADE, to='finddoctor.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='apponiment',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Apponiment',
        ),
    ]
