# Generated by Django 2.1a1 on 2019-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0010_auto_20190427_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='time',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
