# Generated by Django 2.1a1 on 2019-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finddoctor', '0011_auto_20190428_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='time',
            field=models.CharField(default='Add a preferred time', max_length=50),
        ),
    ]
